Update generate_and_publish_dev_blogs.yml

diff --git a/.github/workflows/generate_and_publish_dev_blogs.yml b/.github/workflows/generate_and_publish_dev_blogs.yml
--- a/.github/workflows/generate_and_publish_dev_blogs.yml
+++ b/.github/workflows/generate_and_publish_dev_blogs.yml
@@ -12,7 +12,8 @@ jobs:
       - uses: actions/checkout@v3
       - name: Install pandoc
         run: |
-          sudo apt-get install pandoc
+          sudo apt-get update
+          sudo apt-get install -y pandoc
 
       - name: Generate blog post
         run: |
@@ -28,10 +29,9 @@ jobs:
             echo "HTML file generated successfully."
           else
             echo "Failed to generate the HTML file."
+            exit 1
           fi
-
-      - name: Display files in the current directory
-        run: ls -l
+          ls -l
 
       - name: Upload blog post
         uses: actions/upload-artifact@v2
@@ -44,9 +44,19 @@ jobs:
     needs: generate-blog-post
     steps:
       - uses: actions/checkout@v3
+      - name: Create blog-posts directory
+        run: |
+          sudo mkdir -p /var/www/html/blog-posts
+          sudo chown -R $USER:$USER /var/www/html/blog-posts
       - name: Display files in the current directory
         run: ls -l
       - name: Publish blog post
         run: |
           echo "Publishing blog post..."
-          cp blog_post.html /var/www/html/blog-posts
+          if [ -f "blog_post.html" ]; then
+            cp blog_post.html /var/www/html/blog-posts
+            echo "Blog post published successfully."
+          else
+            echo "Failed to find the HTML file."
+            exit 1
+          fi
